import { Platform } from "react-native";
import { RFPercentage } from "react-native-responsive-fontsize";

export default {

    size: {
        "_1px": RFPercentage(0.118 * 1),
        "_2px": RFPercentage(0.118 * 2),
        "_3px": RFPercentage(0.118 * 3),
        "_4px": RFPercentage(0.118 * 4),
        "_5px": RFPercentage(0.118 * 5),
        "_6px": RFPercentage(0.118 * 6),
        "_7px": RFPercentage(0.118 * 7),
        "_8px": RFPercentage(0.118 * 8),
        "_9px": RFPercentage(0.118 * 9),
        "_10px": RFPercentage(0.118 * 10),
        "_11px": RFPercentage(0.118 * 11),
        "_12px": RFPercentage(0.118 * 12),
        "_13px": RFPercentage(0.118 * 13),
        "_14px": RFPercentage(0.118 * 14),
        "_15px": RFPercentage(0.118 * 15),
        "_16px": RFPercentage(0.118 * 16),
        "_17px": RFPercentage(0.118 * 17),
        "_18px": RFPercentage(0.118 * 18),
        "_19px": RFPercentage(0.118 * 19),
        "_20px": RFPercentage(0.118 * 20),
        "_21px": RFPercentage(0.118 * 21),
        "_22px": RFPercentage(0.118 * 22),
        "_23px": RFPercentage(0.118 * 23),
        "_24px": RFPercentage(0.118 * 24),
        "_25px": RFPercentage(0.118 * 25),
        "_26px": RFPercentage(0.118 * 26),
        "_27px": RFPercentage(0.118 * 27),
        "_28px": RFPercentage(0.118 * 28),
        "_29px": RFPercentage(0.118 * 29),
        "_30px": RFPercentage(0.118 * 30),
        "_31px": RFPercentage(0.118 * 31),
        "_32px": RFPercentage(0.118 * 32),
        "_33px": RFPercentage(0.118 * 33),
        "_34px": RFPercentage(0.118 * 34),
        "_35px": RFPercentage(0.118 * 35),
        "_36px": RFPercentage(0.118 * 36),
        "_37px": RFPercentage(0.118 * 37),
        "_38px": RFPercentage(0.118 * 38),
        "_39px": RFPercentage(0.118 * 39),
        "_40px": RFPercentage(0.118 * 40),
    },
    name: {
        regular: 'NunitoSans-Regular',
        bold: 'NunitoSans-Bold',
        extraBold: 'NunitoSans-ExtraBold',
        medium: 'NunitoSans-Bold',
        semibold: 'NunitoSans-SemiBold',
        light: 'NunitoSans-Light',
        italic: 'NunitoSans-Italic',
        extraLight: 'NunitoSans-ExtraLight',
        SegoeUI_Regular: 'SegoeUI',
        SegoeUI_SemiBold: 'SegoeUI-Semibold',
        OpenSans_Regular: 'OpenSans',
        OpenSans_SemiBold: 'OpenSans-Semibold',
        OpenSans_Bold: 'OpenSans-Bold'
    }

    // name: {
    //     regular: Platform.OS=="android"?'NunitoSans-Regular':undefined,
    //     bold: Platform.OS=="android"?'NunitoSans-Bold':undefined,
    //     extraBold: Platform.OS=="android"?'NunitoSans-ExtraBold':undefined,
    //     medium: Platform.OS=="android"?'NunitoSans-Medium':undefined,
    //     semibold: Platform.OS=="android"?'NunitoSans-SemiBold':undefined,
    //     light: Platform.OS=="android"?'NunitoSans-Light':undefined,
    //     italic: Platform.OS=="android"?'NunitoSans-Italic':undefined,
    //     extraLight: Platform.OS=="android"?'NunitoSans-ExtraLight':undefined,
    //     SegoeUI_Regular: Platform.OS=="android"?"SegoeUI-Regular":undefined,
    //     SegoeUI_SemiBold: Platform.OS=="android"?"SegoeUI-SemiBold":undefined,
    //     OpenSans_Regular: Platform.OS=="android"?"OpenSans-Regular":undefined,
    //     OpenSans_SemiBold: Platform.OS=="android"?"OpenSans-SemiBold":undefined,
    //     OpenSans_Bold: Platform.OS=="android"?"OpenSans-Bold":undefined
    // }
}
